Create Plugin: Drop console statements in production builds
grafana/plugin-tools pull request #1066
Opened 2024-08-20 12:14 UTC by jackw

**What this PR does / why we need it**:
Introduces a setting to the terser plugin to drop console statements for production builds. Should help reduce dev tools noise and make it easier for developers to achieve 💯  against the validator.

Tested the canary build locally against a dev and prod build:

```typescript
import { AppPlugin } from '@grafana/data';
import { App } from './components/App';
import { AppConfig } from './components/AppConfig';

export const plugin = new AppPlugin<{}>().setRootPage(App).addConfigPage({
  title: 'Configuration',
  icon: 'cog',
  body: AppConfig,
  id: 'configuration',
});

console.log('jack jack app!!!');

```

| Dev | Prod | 
| --- | --- |
| <img width="1792" alt="Screenshot 2024-08-20 at 14 24 16" src="https://github.com/user-attachments/assets/6d980279-0dbb-42d8-9f1e-26698116f6c3"> | <img width="1792" alt="Screenshot 2024-08-20 at 14 24 32" src="https://github.com/user-attachments/assets/cceec14a-120e-469a-bbda-2d576ee02907"> |

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/create-plugin@5.3.7-canary.1066.fcc7f3a.0
  npm install @grafana/plugin-e2e@1.7.2-canary.1066.fcc7f3a.0
  npm install @grafana/plugin-meta-extractor@0.0.7-canary.1066.fcc7f3a.0
  # or 
  yarn add @grafana/create-plugin@5.3.7-canary.1066.fcc7f3a.0
  yarn add @grafana/plugin-e2e@1.7.2-canary.1066.fcc7f3a.0
  yarn add @grafana/plugin-meta-extractor@0.0.7-canary.1066.fcc7f3a.0
  ```
</details>

2024-08-20 13:13 UTC, marefr approved these changes
LGTM I guess any real problems should bubble up as exceptions?

2024-08-20 14:50 UTC, academo requested changes
If this is removing console log from source maps this will generate problems with the validator and the source code validation

2024-08-28 08:41 UTC, academo approved these changes
tested and can confirm the console logs are only removed in the built files not the source maps.

2024-08-30 06:45 UTC, sunker approved these changes

2024-08-30 08:27 UTC, jackw commented on packages/create-plugin/templates/common/_package.json
> +    "terser-webpack-plugin": "^5.3.10",
We need this updated version of terser to be able to make fine grained choices of which `console.*` methods to drop.

2024-08-30 08:27 UTC, merged