<FeatureArea>: Add new flag "bundle" to sign command
grafana/plugin-tools pull request #447
Opened 2023-10-04 21:04 UTC by gabrielthomasjacobs

**What this PR does / why we need it**:

When trying to bundle a plugin for submission, the process is manual and can be tedious; especially when making typos or forgetting a step.

This adds a new flag `--bundle` to the sign command. When running the sign command with the bundle flag, this will:

1. Copy the dist folder contents into a folder matching the plugin id (lifted from dist/plugin.json)
2. !!{read note below} update the permissions of the executable files to 0755
3. Zip that folder matching the syntax {pluginId}-{version}.zip, satisfying the submission requirements 
4. Delete the folder created in step 1
5. Calculates and logs the md5 and sha1 of the zipped folder, to make submission simple

**Special notes for your reviewer**:

This doesn't fix #411, but would be a great first-step if accepted; the next step would be to allow a flag value, e.g. `--bundle="multiple"` and then handle that case.

I need some feedback before I can update this PR to be fully review-ready:

+ scaffolding and zipping works on *nix and windows systems. Setting permissions on windows without WSL *won't* work due to how windows manages permissions. WSL works just fine though. I tried to leave as much of the script to be cross-platform compatible, since the Readme for the sign-plugin says that it works on all 3 systems... I can throw an error instead of a warning if on win (non-WSL) since the permissions won't work.

+ I placed this as a flag for the sign command, since the workflow is going to be sign -> bundle for the vast majority of the user workflows and the sign command already has the dist dir set. I can break this out into a fully new command though if that would be preferred.  
- The permission setting is giving me some issues; chmodsync seems to only be outputting 0777 as the permission level. I'm still looking into this, but wanted to get some initial feedback on this PR and maybe someone knows why it's not setting it properly. 
- Will add documentation corresponding to feedback on other points (if viable feat and if should be separate command or not)

2023-10-04 21:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/plugin-tools?pullRequest=447) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/plugin-tools?pullRequest=447) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/plugin-tools?pullRequest=447) it.</sub>

2023-10-24 12:16 UTC, sympatheticmoose requested changes
Hi @gabrielthomasjacobs apologies for the delay in getting back to you. This is a good idea and thank you for taking the initiative to propose the fix. I'd recommend raising issues for enhancements first, this way we can provide some feedback or guidance before any code gets written. 

This probably goes beyond the scope of responsibilities for `sign-plugin`, but could be provided through a different mechanism - our recommendation would be a script which could be distributed within `.config`.  I've raised https://github.com/grafana/plugin-tools/issues/491 to track this request.

2023-10-27 00:45 UTC, gabrielthomasjacobs commented
Ok, thanks @sympatheticmoose for the feedback and for creating #491, I'll subscribe to that ticket and wait for triage/feedback!

2024-02-06 17:41 UTC, closed without merging

2024-02-13 17:58 UTC, sympatheticmoose commented
Hey @gabrielthomasjacobs - wrt the adv build action and the zips per architecture - I'm curious if this was a feature of interest to you and if you had a use case for it?

2024-02-13 20:35 UTC, gabrielthomasjacobs commented
Hey @sympatheticmoose, I'm planning on using the github actions to handle the building/releasing as described in https://github.com/grafana/plugin-actions/blob/main/build-plugin/action.yml

As for the multiple zips, it would be a nice to have, but it's my understanding that community plugins aren't currently supported for this type of distribution.