Docs: Replace DocCardLists with DocLinkLists
grafana/plugin-tools pull request #526
Opened 2023-11-03 22:43 UTC by josmperez

This PR utilizes the DocLinkLists added in https://github.com/grafana/plugin-tools/pull/493 to the site's index pages. Add two index pages for develop-a-plugin and extend-a-plugin.

2023-11-04 11:02 UTC, marefr approved these changes
LGTM

2023-11-06 09:46 UTC, sympatheticmoose requested changes
I don't think this works yet, doclinklist doesn't support folders.

This impacts:
- tutorials
- create a plugin
- migration guides

We can discuss more with Jack when he's back

PR: <img width="1044" alt="Screenshot 2023-11-06 at 09 47 45" src="https://github.com/grafana/plugin-tools/assets/19860021/b4597355-9e5b-48df-955b-12cc1852ffaa">

Live: 
<img width="1063" alt="Screenshot 2023-11-06 at 09 48 13" src="https://github.com/grafana/plugin-tools/assets/19860021/c8b9e84d-35e2-4cbd-9b8b-34981e52c442">

2023-11-15 10:49 UTC, jackw commented
>how does it look for /migration-guides which has a mixture of folders and pages?

Right now it looks like the screenshot below which is a little misleading as it suggests the update create-plugin versions and migrate from toolkit are angular related. I can separate them in someway, just not entirely sure how off the top of my head. 😄 

![image](https://github.com/grafana/plugin-tools/assets/73201/bb4ce6ef-a09b-4113-b13f-1c622d303629)

2023-11-15 11:15 UTC, sympatheticmoose commented
Figured that might be the case 😄 hmm, personally I would just go the titles and use of custom metadata for now. I'm not convinced its worth worrying too much over. 

> link to first item in category

To work around having to pick we can always just add the `_index` file with `DocLinkList` for the ones which lack it:
- upgrade from grafana versions
- develop a plugin
- extend a plugin

2023-11-15 11:38 UTC, jackw commented
> hmm, personally I would just go the titles and use of custom metadata to indicate its a collection of content for now. I'm not convinced its worth worrying too much over.

Just to confirm, we'd be happy to add the customProps.description to each `_category_.json` and for it to look like this:

![image](https://github.com/grafana/plugin-tools/assets/73201/1a92dfb2-3d4f-4a02-8dce-acf0dc199f62)

2023-11-15 12:18 UTC, sympatheticmoose commented
I'm happy with that

2023-11-15 19:15 UTC, josmperez commented
> we'd be happy to add the customProps.description to each `_category_.json` and for it to look like this:

looks good

2023-11-16 09:03 UTC, jackw commented
@josmperez I've pushed a commit to this branch that updates the DocLinkList component as we've discussed above. To add descriptions in category links you'll need to update the `_category_.json` files with `customProps.description`. Example below:

```diff
{
  "position": 1,
  "label": "Develop a plugin",
+  "customProps": {
+    "description": "Category description text."
+  },
  "collapsible": true,
  "collapsed": true
}
```

2023-11-22 14:21 UTC, sympatheticmoose approved these changes
minor suggestions, no blockers 🚀

2023-11-22 14:21 UTC, sympatheticmoose commented on docusaurus/docs/create-a-plugin/_category_.json
I don't think this is needed but theres no harm in having it.

@jackw I assume these are optional and only needed if the page/category is going to be included within a DocLinkList (which to my knowledge this isn't). Is there any other benefit to the metadata?

2023-11-22 14:21 UTC, sympatheticmoose commented on docusaurus/docs/create-a-plugin/extend-a-plugin/_category_.json
> +    "description": "Guides for extending a Grafana plugin with features such as authentication, query editor help, and annotations."
```suggestion
    "description": "Guides for extending your Grafana plugin with additional features to improve its quality."
```

2023-11-22 14:21 UTC, sympatheticmoose commented on docusaurus/docs/migration-guides/angular-react/_category_.json
> +    "description": "How to migrate your plugin from Angular to ReactJS."
```suggestion
    "description": "How to migrate your plugin from the legacy AngularJS framework to our React based platform."
```

2023-11-22 14:21 UTC, sympatheticmoose commented on docusaurus/docs/migration-guides/update-from-grafana-versions/_category_.json
> +    "description": "How to update your plugin from one version of Grafana to another."
```suggestion
    "description": "How to handle breaking changes between Grafana versions in your plugin."
```

2023-11-22 14:21 UTC, sympatheticmoose commented on docusaurus/docs/tutorials/_category_.json
Again, not sure we need this but no harm in keeping

2023-11-22 22:08 UTC, merged