angular to react configuration migration guide
grafana/plugin-tools pull request #664
Opened 2024-01-12 20:56 UTC by briangann

**What this PR does / why we need it**:

Adds how-to guide for angular plugins migrating to react

2024-01-16 23:09 UTC, josmperez commented
Hi, great job. I have completed a first pass editorial review. Please review the latest commit with proposed changes and ensure that no inaccuracies have been introduced. I will begin a second pass later this week or when the PR gets out of "Draft" state.

2024-01-22 23:39 UTC, briangann commented
@josmperez ready for a second pass!

2024-02-06 19:40 UTC, josmperez requested changes
Hi Brian, I have made a second editorial pass, this one focused on structure (there were some issues with headings not being explanatory enough).

2024-02-06 19:41 UTC, josmperez commented on docusaurus/docs/migration-guides/angular-react/configuration-migration.md
> +#### Case 1: User runs panel with Roboto selected
```suggestion
#### Case 2: User runs panel with Roboto selected
```

2024-02-07 04:36 UTC, briangann commented
not sure why this is blocked with a request pending, if we're good to go Joe i'll force the merge.

2024-02-07 04:38 UTC, josmperez commented
Okay, sounds good

On Tue, Feb 6, 2024 at 8:37 PM Brian Gann ***@***.***> wrote:

> not sure why this is blocked with a request pending, if we're good to go
> Joe i'll force the merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/plugin-tools/pull/664#issuecomment-1931267372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK5BGRCRGT7G4Q5K7TV6WXLYSMAHJAVCNFSM6AAAAABBYWIE2CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZRGI3DOMZXGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-07 04:46 UTC, merged